# Generated by Django 4.1 on 2024-03-03 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GroupData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("payment", models.CharField(max_length=100)),
                ("time", models.CharField(max_length=100)),
                ("orderLink", models.CharField(max_length=100)),
                ("personCount", models.CharField(max_length=100)),
                ("hostName", models.CharField(max_length=100)),
            ],
        ),
    ]
